[default]
extend-ignore-words-re = [
    # words with length <= 4 chars is likely noise
    "^[a-zA-Z]{1,4}$",
]

[files]
extend-exclude = [
  "static",
  "templates/blocks/ai-*.html",
]

# https://github.com/crate-ci/typos/issues/1304#issuecomment-3188457455
[type.css.extend-words]
wdth = "wdth"
[type.html.extend-words]
wdth = "wdth"
