name: Build

on:
  workflow_call:
    # https://docs.github.com/actions/using-workflows/sharing-workflows-secrets-and-runners-with-your-organization
    # https://docs.github.com/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_callinputs
    inputs:
      dry-run:
        description: 'Skip deployment (just build)'
        default: ${{ github.event_name == 'pull_request' }}
        required: false
        type: boolean
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/build.yml"
      - "app"
      - "content"
      - "public"
      - "*.lock"
      - "*.nix"
      - "*.ts"
      - "*.json"
  pull_request:
    types: [synchronize, opened, reopened]
    paths:
      - ".github/workflows/build.yml"
      - "app/**"
      - "content/**"
      - "public/**"
      - "*.lock"
      - "*.nix"
      - "*.ts"
      - "*.json"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@v11
        with:
          send-statistics: false
    
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v18
        with:
          logger: pretty
          diagnostic-endpoint: ""
          
      - name: Build Site
        run: nix build -L
      
      - name: Upload Pages Artifact
        if: (!inputs.dry-run)
        uses: "actions/upload-pages-artifact@v3.0.1"
        with:
          name: site
          path: result
          # Default is 90 days, let ensure we don't use stale builds:
          retention-days: 2
